version: '3'

services:
    app:
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - database
    database:
        image: postgres:12.3-alpine
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=django_app
            - POSTGRES_PASSWORD=django_app
            - POSTGRES_DB=django_app
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        ports:
            - 3000:3000
        command: "npm start"
        tty: true
        volumes:
            - ./frontend/src:/app/src/
            - ./frontend/public:/app/public/
        depends_on:
            - app
volumes:
    postgres_data:
    src:
    public: